version: "3.7"
services:
  elasticsearchservice:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    networks:
      - elasticnetwork
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=recipe-cluster
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always
  kibanaservice:
    image: kibana:7.17.6
    container_name: kibana-container
    networks:
      - elasticnetwork
    ports:
      - 5601:5601
    restart: always
volumes:
  es-data:
networks:
  elasticnetwork:
    name: elasticnetwork